### ISSUE TITLE
Inconsistencies

### ISSUE THREAD

**Issue by correnson** [OCamlPro/alt-ergo#10]
The following goal is discharged by alt-ergo:

```
logic safe_comp_div: int, int -> int

axiom def1:
  forall x, y:int.
  x >= 0 and y > 0 -> safe_comp_div(x,y) = (x / y)

axiom def2:
  forall x, y:int [safe_comp_div(x,y)].
  x <= 0 -> y > 0 -> safe_comp_div(x,y) = -((-x) / y)

logic r: int

goal test_split_assert_absurd:
 let x = (safe_comp_div(5, 2)) : int in
 (x = r) ->
 false
```

The issue disappears with _any_ of the following modifications:
 - changing division by multiplication
 - using the default trigger in 'def2'
 - changing the 'and' by '->' in 'def1'
 - removing the equality 'x=r' in goal

Looks like a very low-level bug...
L.

**Comment by iguer** [comment]
Thanks for reporting the bug.
Although I was not able to replay it with the current version, the origin of the bug was still there. It's now fixed.
- Mohamed.

**Comment by correnson** [comment]
Ok thanks !
