### ISSUE TITLE
Remove the pin on Ocplib-simplex

### ISSUE THREAD

**Issue by Halbaroth** [OCamlPro/alt-ergo#1077]
In #1068, we will add a pin on the commit https://github.com/OCamlPro/ocplib-simplex/commit/50996ec8142bf9deef383cbbc774cf46d639b371 of Ocplib-simplex. We have to remove this pin before releasing the next version of Alt-Ergo and we have to release a minor version of Ocplib-simplex before.

**Comment by bclement-ocp** [comment]
Maybe we should just make an ocplib-simplex patch release now and be done with it?
