### ISSUE TITLE
version number for binary releases

### ISSUE THREAD

**Issue by Armael** [OCamlPro/alt-ergo#1131]
There seems to be an issue with how binary releases are produced, in that the `--version` they return is the hash of the corresponding git commit, instead of a version number.
This is problematic because : 
- it is not consistent with binaries produced when installing alt-ergo through opam
- it makes why3 fail to detect the alt-ergo version (since why3 is expecting `--version` to behave as it does for opam-built releases)

**Comment by bclement-ocp** [comment]
Looks like this no longer works somehow? Re-opening; need to investigate before 2.6 release.

**Comment by bclement-ocp** [comment]
Actually it works but not if the release is created by GitHub UI (sigh).
