### ISSUE TITLE
Discrepancy between the legacy frontend and the Dolmen frontend

### ISSUE THREAD

**Issue by Halbaroth** [OCamlPro/alt-ergo#1161]
Consider the following input in native language:
```
type 'b sy = { V : 'b }

function rename(u: 'b sy, s: ('b,'c) farray) : 'c sy = { V = s[u.V] }

logic f : ('b,'b sy) farray

goal g:
  forall t:int.
  forall s1:(int,int) farray.
  forall s2:(int,int) farray.
  s1[t] = s2[t] ->
  rename({ V = t }, s1) = rename({ V = t }, s2)
```
Alt-Ergo answers `Valid` with Dolmen frontend in both `v2.5.4` and `next` but `I don't know` with the legacy frontend. 
If we inline the definition of `rename` in the goal as follows:
```
goal g:
  forall t:int.
  forall s1:(int,int) farray.
  forall s2:(int,int) farray.
  s1[t] = s2[t] ->
  s1[t] = s2[t]
```
 Alt-Ergo answers `Valid` in all the cases.

**Comment by Halbaroth** [comment]
The issue comes from a monomorphization phase performed in the legacy typechecker. If we help the legacy frontend by adding type annotations as follows:
```
type 'b sy = { V : 'b }

function rename(u: 'b sy, s: ('b,int) farray) : int sy = { V = s[u.V] }

logic f : ('b,'b sy) farray

goal g:
  forall t:int.
  forall s1:(int,int) farray.
  forall s2:(int,int) farray.
  s1[t] = s2[t] ->
  rename({ V = t }, s1) = rename({ V = t }, s2)
```
Both legacy and Dolmen frontends answer `unsat`. 
Without these type annotations, while typing the goal, the legacy frontend monomorphizes the
the type of the term `rename({ V = t }, s1)` to `'_c14 sy` where `'_c14` is a fresh uninterpreted type. The matching module cannot trigger the axiom associated to `rename` because the type variable `'c` cannot be unified with the uninterpreted type `'_c14`.

**Comment by Halbaroth** [comment]
After a long dive, I found the exact problem. The legacy typechecker does not type correctly polymorphic records. For instance, it will accept the following input:
```
type 'b sy = { V : 'b }

function rename(u: 'b sy, s: ('b,int) farray) : real sy = { V = s[u.V] }

logic f : ('b,'b sy) farray

goal g:
  forall t:int.
  forall s1:(int,int) farray.
  forall s2:(int,int) farray.
  s1[t] = s2[t] ->
  rename({ V = t }, s1) = rename({ V = t }, s2)
```
Notice the return type of `rename`.

**Comment by bclement-ocp** [comment]
Given that Dolmen is the default typechecker in 2.6 and the legacy typechecker will be removed in 2.7, we don't need to fix bugs in the legacy typechecker.

**Comment by Halbaroth** [comment]
Actually, I did it because I want to be sure that there is no regression in #1160 and to understand the slow down observed with Dolmen. I have a patch and an explanation of the issue now. After the patch, there is almost no difference between the legacy and the Dolmen frontend. 

The issue comes from the function `Ty.fresh`. This function is supposed to generate fresh type variables for all the type variables occurring in the input type. Basically, a part of the union find of the legacy typechecker is directly stored in types of `Ty`. There are two kind of `Tvar`:
1. Truly free type variable represented by a `Tvar` with a `value` field equal to `None`
2. Link to the another type which is the representative element of the class in the union-find.

The function `Ty.unify` performs a destructive unification, which means we have to generate fresh type variables before calling it if we want to perform a unification in a local context... 

The purpose of `Ty.shorten` is to perform path compression and normalization. The bug comes from the fact `Ty.fresh` treats the two kind of `Tvar` in the same way: it generates a completely fresh type variable for both of them. So we lost information here. The patch consists to call `Ty.shorten` before generating fresh variables.
