### ISSUE TITLE
Link to build instructions from README leads to nowhere

### ISSUE THREAD

**Issue by barracuda156** [OCamlPro/alt-ergo#1196]
https://ocamlpro.github.io/alt-ergo/Install/index.html

> 404
> File not found

**Comment by bclement-ocp** [comment]
Thanks for your interest in Alt-Ergo — README links were forgotten when we switched to versioned documentation recently. The correct link for the latest release is now here: https://ocamlpro.github.io/alt-ergo/latest/Install/index.html
