### ISSUE TITLE
Axiomatisation de \list en Alt-ergo

### ISSUE THREAD

**Issue by pbaudin** [OCamlPro/alt-ergo#12]
Bonjour,

Dans la dernière version de Frama-C, un type ACSL polymorphe prédéfini \list a été ajoute, avec une axiomatique suggérée par l'équipe de Claude.
Cependant, des preuves considérées comme triviales ne sont pas réalisées par Alt-Ergo.

Vous trouverez ci-joint un exemple contenant deux buts similaires, l'un prouvé et pas l'autre.
Ils sont du genre forall i: int . 0 <= i < N -> f(i) == la-valeur-du-i-ème-élément-de-la-liste [ f(0) , f(1), ... f(15) ].
Sur ma machine, Alt-Ergo 0.99.1 les prouvent pour N allant de 0 à 11.
Ca ne se prouve plus au dela.

Comment expliquez-vous cela ?
Est-ce le cas avec votre version de développement ?
Si oui, quelle en est la raison de cet échec ?
Existe-t-il un contournement à ce problème ?

Cordialement,
Patrick Baudin
[nth.txt](https://github.com/OCamlPro/alt-ergo/files/108069/nth.txt)

.

> alt-ergo -version
0.99.1
> alt-ergo nth.mlw
File "nth.mlw", line 106, characters 1-681:Valid (0.0343) (36)
File "nth.mlw", line 129, characters 1-681:I don't know.

**Comment by OCamlPro-Iguernlala** [comment]
Bonjour Patrick,

Le second but n'est pas prouvé à cause de l'heuristique `-age-bound` qui limite l'utilisation les termes d'une génération trop lointaine (i.e. résultant de l'instantiation d'instantiation ..... d'instantiation d'axiomes). Sa valeur par défaut est `10`.

Les deux buts sont prouvés avec `-age-bound 100` (ou même `11`)
 
```
$ alt-ergo nth.why -age-bound 1000
File "nth.why", line 106, characters 1-681:Valid (0.0840) (36)
File "nth.why", line 129, characters 1-681:Valid (0.0600) (75)
```

Je vais voir si augmenter (voir supprimer) cette heuristique cause trop de régressions sur notre suite de benchs ou pas. Si si n'est pas le cas, on peut envisager de l'alléger.

Mohamed.

**Comment by pbaudin** [comment]
Bonjour Mohamed,

Merci pour ce retour.

Ensuite, je ne considère pas cette PO comme représentative de nos POs, 
mais juste comme une instance très simplifiée.
Bref, c'est juste un cas d'école...

Enfin, pour augmenter la valeur passée à votre option "-age-bound", il 
nous est possible d'utiliser l'option "-wp-depth" du greffon WP de Frama-C.
Actuellement, sa valeur par défaut est "0". Elle conduit le WP à ne pas 
utiliser "-age-bound" afin qu'Alt-Ergo choisisse, pour le mieux, cette 
valeur.

Bien cordialement,
Patrick.
