### ISSUE TITLE
Package Debian

### ISSUE THREAD

**Issue by Halbaroth** [OCamlPro/alt-ergo#1215]
In our documentation we suggest to install Alt-Ergo with `apt-get` but the latest version available on Debian is `2.0.0`: 
https://packages.debian.org/search?keywords=alt-ergo

I suggest to remove this mention in our documentation.

**Comment by bclement-ocp** [comment]
Yes let's drop it. Alt-Ergo has been removed from the Debian repositories in the latest stable version.
