### ISSUE TITLE
Support dolmen frontend in JS worker

### ISSUE THREAD

**Issue by bclement-ocp** [OCamlPro/alt-ergo#1232]
> I think Try Alt-Ergo is currently broken but I don't think that should block the release.

More precisely `worker_js.ml` does not seem to be compatible with dolmen.

_Originally posted by @bclement-ocp in https://github.com/OCamlPro/alt-ergo/issues/1218#issuecomment-2331036717_

**Comment by Halbaroth** [comment]
When I try to run the worker example as follows:
```dune exec -- src/bin/js/worker_example.exe``` 
I got:
```
Fatal error: Unimplemented Javascript primitive caml_js_expr!
fish: Job 1, 'dune exec -- src/bin/js/worker_…' terminated by signal SIGABRT (Abort)
```
Is it the issue you ran into?

**Comment by bclement-ocp** [comment]
I don't think calling `src/bin/js/worker_example.exe` is supposed to work. The way to run the js example is to build with `make js-example` and then run from the `www` directory.

The issue is that the worker always uses the legacy frontend, but tries to find a "dolmen" type. The easy fix is to force the use of the "legacy" frontend in the JS worker; the long-term fix is to modify the JS worker to use the dolmen frontend instead of the legacy frontend.

**Comment by bclement-ocp** [comment]
The way I run the worker is as follows (you can't simply open the `www/index.html` file; you run into restrictions in the browser that refuses to execute javascript from the file:// protocol):

```console
$ make js-example
$ python -m http.server -d www
```

Sending a file with "Ask Alt-Ergo" returns an error in the dev console:
```
{ "worker_id": 42, "status": { "Error": "Unknown error" } }
```

and if I print the exception in `src/bin/js/worker_js.ml`:

```diff
diff --git a/src/bin/js/worker_js.ml b/src/bin/js/worker_js.ml
index 4d79920d..484d7812 100644
--- a/src/bin/js/worker_js.ml
+++ b/src/bin/js/worker_js.ml
@@ -259,11 +259,11 @@ let main worker_id content =
       Worker_interface.diagnostic =
         Some [Format.asprintf "%a" Errors.report e]
     }
-  | _ ->
+  | exn ->
     let res = Worker_interface.init_results () in
     { res with
       Worker_interface.worker_id = worker_id;
-      Worker_interface.status = Error "Unknown error";
+      Worker_interface.status = Error ("Unknown error: " ^ Printexc.to_string exn);
     }
 
 (** Worker initialisation

```

we get a more detailed error:

```
{ "worker_id": 42,
  "status":
    { "Error":
        "Unknown error: AltErgoLib.Input.Method_not_registered(\"dolmen\")" } }
```

**Comment by Halbaroth** [comment]
Done in #556
