### ISSUE TITLE
Please clarify the license

### ISSUE THREAD

**Issue by vbgl** [OCamlPro/alt-ergo#127]
IIUC alt-ergo-2 is unfree. For instance, I cannot build it and distribute the resulting binary program.

However, on [why3-club](https://lists.gforge.inria.fr/pipermail/why3-club/2017-November/001611.html), Mohamed Iguernlala wrote:

> there will be a free version of Alt-Ergo 2.0.0 that can be included in Debian.

Will that ever happen? If so do you know when?

Thanks.

**Comment by OCamlPro-Iguernlala** [comment]
alt-ergo >= 2.0 is free for academia usage (but not free in the sens of OSI).

I wrote that there will be a free version based on Alt-Ergo 2.x.x.

**Will that ever happen?**
I would say yes

**If so do you know when?**
I don't. Maybe before 2019, maybe after...
