### ISSUE TITLE
Error: Invalid_argument("equal: abstract value") triggered with "-complete-model" option

### ISSUE THREAD

**Issue by j123123** [OCamlPro/alt-ergo#13]
``Error: Invalid_argument("equal: abstract value")`` happens when try to get prof of this code using Frama-C with alt-ergo
````
/*@ ensures \result == (uint8_t)(op1+op2);
*/
uint8_t bit_sum_2(uint8_t op1, uint8_t op2)
{
  if ((op1 < 4) && (op2 < 4))
  {
    return (((op1>>1) + (op2>>1))<<1) + (op1-((op1>>1)<<1)) + (op2-((op2>>1)<<1));
  }
  return op1 + op2;
}
````
here is mlw [bit_sym.txt](https://github.com/OCamlPro/alt-ergo/files/179033/bit_sym.txt)
Try it with ``-complete-model`` option

**Comment by OCamlPro-Iguernlala** [comment]
Hello, can you tell us:
(1) which version of Alt-Ergo are you using,
(2) on which platform (Linux, Windows, or Mac),

Because, I tried with versions 1.01, 0.99.1, and 0.95.2 on Linux, and the issue is not there

**Comment by j123123** [comment]
```
$ altgr-ergo -version
0.95.2
```
I tried it on Ubuntu 14.04.4 LTS

**Comment by OCamlPro-Iguernlala** [comment]
It's better to update to the latest version (for instance via OPAM)

**Comment by j123123** [comment]
Thanks, version 1.01 works fine
