### ISSUE TITLE
OPAM: pinning to dev-repo does not work

### ISSUE THREAD

**Issue by OriginLabs-Iguernlala** [OCamlPro/alt-ergo#134]

**Comment by Gbury** [comment]
So, one option to fix this problem would be to move the 4 `*.opam` files currently in `sources` to the root of the repo (as well as the `dune-project` file). However, that would break the fact that releases currently only depend on files in the `sources` directory.

**Comment by OCamlPro-Coquera** [comment]
This should be fix in #287
