### ISSUE TITLE
some fundamental problem with division (division by 0)

### ISSUE THREAD

**Issue by j123123** [OCamlPro/alt-ergo#15]
Here is the problem:
```
(* this goals is proveable. Strange *)
goal test_nativediv_1:
  forall x,y : int.
  x/y = x/y

goal test_nativediv_2:
  forall x,y : int.
  x/0 = x/0

(* define my own safe division without division by zero *)
logic safe_div : int, int -> int

axiom safe_div : forall x,y : int. (y <> 0) -> x/y = safe_div(x,y)

(* 
Should be unprovable because safe_div is not defined for y = 0
 but it still can prove it. What wrong?
*)
goal test_safe_div_1:
  forall x,y : int.
  safe_div(x,y) = safe_div(x,y)

goal test_safe_div_2:
  forall x : int.
  safe_div(x,0) = safe_div(x,0)
```

**Comment by j123123** [comment]
for example, this cannot be proven 
```
(* allow_any_except_zero *)
logic aaez : int -> int

axiom aaez_axiom : forall x : int. (x <> 0) -> aaez(x) = x

goal allow_zero:
  forall x : int.
  aaez(x) = x
```

**Comment by j123123** [comment]
I think I need three-valued logic to do this.

**Comment by OCamlPro-Iguernlala** [comment]
From a logical point of view, all these goals except allow_zero are provable.

Every function symbol `F` (including safe_div and /) have at least the reflexivity, symmetry, transitivity, and congruence property. So, whenever some `a` is equal to some `b`, the equality `F(a) = F(b)` follows by congruence.

**Comment by j123123** [comment]
@OCamlPro-Iguernlala 
I think I need  Kleene's weak three-valued logic: https://en.wikipedia.org/wiki/Many-valued_logic#Bochvar.27s_internal_three-valued_logic_.28also_known_as_Kleene.27s_weak_three-valued_logic.29 
For example, if I need to make unprovable this equation
<img src="http://www.sciweavers.org/tex2img.php?eq=%24%24%20%5Cfrac%7Bx%7D%7By%28y%2B1%29%28y%2B2%29%7D%20%3D%20%24%24%20%5Cfrac%7Bx%7D%7By%28y%2B1%29%28y%2B2%29%7D&bc=White&fc=Black&im=jpg&fs=12&ff=arev&edit=0"/>
I need this 3-valued logic.
```
goal check_div_0:
  forall x,y : int.
  3_order_to_bool(3_compare(
     3_div(x,3_mul( y , 3_mul(3_plus(y,1),  3_plus(y,2) )  )),
     3_div(x,3_mul( y , 3_mul(3_plus(y,1),  3_plus(y,2) )  ))
      )
```
I need theory of enumeration types
```
type l3 = TRUE | FALSE | UNDEFINED

logic 3_compare : l3, l3 -> l3
```
And I need polymorphic records... I mean. If I divide anything into anything except zero and UNDEFINED, I need to get int type in the result. Otherwise, I get UNDEFINED. And if I "add sub mul div mod" with UNDEFINED -> I get UNDEFINED.

Does alt-ergo have some core 3-valued logic? Or I need to define it by myself?

**Comment by OCamlPro-Iguernlala** [comment]
No, Alt-Ergo does not have 3-valued logic, and I'm not sure that using this kind of logic is a good idea. I'm not a specialist of this kind of encodings, but I think there are simpler ways of dealing with this situation.

You would get more help on Why3 or Frama-C mailing lists I think.
