### ISSUE TITLE
Strange behavior with ac

### ISSUE THREAD

**Issue by correnson** [OCamlPro/alt-ergo#16]
We faced strange behaviors related to the attached files (alt-ergo 1.01)

 - File `found.mlw`: declaring `land ac` or `land` has no impact (goal proved) ;
 - File `notfound.mlw` : with `land` not `ac` the goal is proved, but declaring `land ac` make the proof not found and altgr-ergo crashing ;
 - The only difference with the two files is a permutation of the hypotheses in the goal.

[bug.zip](https://github.com/OCamlPro/alt-ergo/files/217395/bug.zip)

**Comment by OCamlPro-Iguernlala** [comment]
Thank you for reporting this bug. It was quite hard to debug...

 The behaviors was due to a weakness in the cooperation between AC and CC theories (from an implementation point of view) that was sensitive to the order of facts. It is now fixed.

- Mohamed.

**Comment by correnson** [comment]
Great job!
