### ISSUE TITLE
unsound proof of VC with euclidian division

### ISSUE THREAD

**Issue by yannickmoy** [OCamlPro/alt-ergo#17]
The VC below is proved by Alt-Ergo, although it should not be provable. I believe there is somewhere a bug with how division and modulo (/ and %) are treated in Alt-Ergo, which may not be consistent with the definition of SMT-LIB. CVC4 and Z3 do not prove this goal (in SMT-LIB logic). I tried with both 1.01 and Clement used the latest version, with the same issue. What should be provable is that z is between 6 and 7, not that z has value 6. This VC comes from SPARK code checking the value of fixed-point computations.

logic comp_div: int, int -> int
axiom comp_div_def: forall x, y:int. x >= 0 and y > 0 -> comp_div(x,y) = x / y

axiom Div_mod1 :
  (forall x:int. forall y:int. ((not (y = 0)) ->
  (x = ((y * (x / y)) + (x % y)))))

logic abs : int -> int

axiom Mod_bound1 :
  (forall x:int. forall y:int. ((not (y = 0)) -> ((0 <= (x % y)) and
  ((x % y) <  abs(y)))))

predicate pos_div_relation(res: int, num: int, den: int) =
  (comp_div(num,den) <= res) and (res <= (comp_div(num,den) + 1))

logic fxp_div : int, int -> int

axiom fxp_div_def :
  (forall x:int.
  (forall y:int [fxp_div(x, y)].
  (((0 <  x) and (0 <  y)) -> pos_div_relation(fxp_div(x,y), (x * 4), y))
  and
  (((x < 0) and (y < 0)) -> pos_div_relation(fxp_div(x,y), ((-x) * 4), (-y)))
  ))

logic x : int
logic y : int
logic z : int

goal fixed:
   x = 5 -> y = 3 -> z = fxp_div(x,y) -> z = 6

**Comment by OCamlPro-Iguernlala** [comment]
Thanks for reporting the bug. I'll try to understand how Alt-Ergo manages to prove the example.

**Comment by yannickmoy** [comment]
Hi Mohamed, any news on this issue?

**Comment by OCamlPro-Iguernlala** [comment]
Hi Yannick,

I found the origin of the bug, and I fixed it 3 days ago. It was due to an incorrect rounding (floor instead of ceiling) when doing Euclidean division with negative numbers. This patch will in the next public release of Alt-Ergo (available soon).

**Comment by yannickmoy** [comment]
Very good news! What is the approximate timeframe for the next public release? February like last year?

**Comment by OCamlPro-Iguernlala** [comment]
Rather in the next few days if I manage to find some time to do necessary checks before the release.
