### ISSUE TITLE
[IntervalCalculus] Assertion failed, line 231

### ISSUE THREAD

**Issue by iguerNL** [OCamlPro/alt-ergo#185]
Commit ID: ac84c736c27b1f1d3ede360d0a36e9b40d8899b2

File: AE-format/why3-no-split/binary_multiplication-BinaryMultiplication63-VC_binary_mult.ae.zip

Reason: case-split for an integer expression extracted from the simplex is a non-integer constant, although it's equal to min/max bound.

**Comment by Stevendeo** [comment]
I did not manage to reproduce the error, it may have been fixed already. How long did Alt-Ergo run before raising the assertion ? Did you use any options ?

**Comment by bclement-ocp** [comment]
Same note as @Stevendeo, I cannot reproduce. This has probably been fixed sometime in the last 5 years, closing.
