### ISSUE TITLE
add a new PSMT2 frontend that directly produces assertions of type Expr.t

### ISSUE THREAD

**Issue by iguerNL** [OCamlPro/alt-ergo#186]
Current PSMT2 frontend generates a native Alt-Ergo parsed AST that is (re-)typechecked before generating assertions of type `Expr.t`. However, since triggers are now computed in module `Expr`, a better PSMT2 frontend would directly generate assertions of type `Expr.t`

**Comment by Gbury** [comment]
With the recent merge of #191 it should now be possible for the psmt2 frontend to directly produce terms of type `Typed.t` (by registering a new frontend/input method).
So the question becomes whether the `Typed.t` type should disappear in favor of `Expr.t` ?

**Comment by bclement-ocp** [comment]
The existing PSMT2 frontend is deprecated and will be replaced with the Dolmen frontend in the future. The Dolmen frontend already generates `Expr.t` directly (and can be in a way considered as the "new PSMT2 frontend" described in this issue). Closing.
