### ISSUE TITLE
Alt-ergo proves both "A" and "A ->R", but gives a counter-example SAT model for "R"

### ISSUE THREAD

**Issue by Jochen-Burghardt** [OCamlPro/alt-ergo#19]
I ran Alt-ergo (version 1.30) on the following file:
```
(* proven from {}: *)
(* axiom arith:
  forall a, i : int.
  a+8-i = a+(8-i)
*)
(* disproven from {}, but proven from {arith}: *)
goal reverse:
  forall s,t : (int,int) farray.
  forall a : int.
  (forall i : int. (0<=i) -> (i<9) -> (t[a+i] = s[a+8-i])) ->
  (forall i : int. (0<=i) -> (i<9) -> (s[a+i] = t[a+8-i]))
```
Alt-ergo immediately said "`I don't know`"; when I supplied the command line option `-all-models` it printed "`SAT model found`", followed by some inequations that apparently are intended to be a counter-example (but in fact are not, i.m.h.o.).

When I commented-in the axiom `arith`, Alt-ergo proved the goal `reverse`.
However, `arith` itself can be proven by Alt-ergo without needing any (user-supplied) preconditions.
For the latter reasons, I think the SAT model cannot be a proper counter-example.

**Comment by OCamlPro-Iguernlala** [comment]
In your (inlined) axiom `(forall i : int. (0<=i) -> (i<9) -> (t[a+i] = s[a+8-i]))`, the only possible triggers are  `t[a+i]` and `s[a+8-i]`. However the terms `s[a+i]` and `t[a+8-i]` modulo equality (only).

In fact, a simple arithmetic reasoning which says that `(a+8)-i = a+(8-i)` is required to enable the generation of the instance that allows to do the proof. Since matching modulo equality+arithmetic is not supported by the solver, this equality should be given.

For the models, Alt-Ergo always shows "model candidates", in particular in presence of universally quantified formulas.

**Comment by Jochen-Burghardt** [comment]
I'm not familiar with the details of SAT mod. theory solving, so I don't quite understand the notion of a trigger. 
Also, I don't know what exactly you mean by "model candidates". I assumed that the printed "SAT model" is an assignment that satisfies (mod. theory) the formula given to Alt-Ergo, i.e. the negation of my goal formula. If I'm wrong here, please correct me.
In any case, I wonder which theory is supported by Alt-Ergo, and, more important, if it is complete for that theory. (Doesn't the above example demonstrate some incompleteness wrt. Presburger arithmetic plus farrays?)
Is there a User's Manual where I can find some answers to these questions? I didn't find any on the Alt-Ergo site or in the source distribution.

**Comment by OCamlPro-Iguernlala** [comment]
1/ When one talks about a theory in SMT, it is (in general) for solving/deciding quantifier-free formulas. So, the combination of quantifiers-free linear arithmetic with arrays is complete in Alt-Ergo.

However, you have universally quantified fragments in your example. In fact, your goal is equivalent to this one:

```
logic s,t : (int,int) farray
logic a : int

axiom my_inlined_axiom :
  forall i : int. (0<=i) -> (i<9) -> (t[a+i] = s[a+8-i])

logic i_skolem : int

goal reverse:
  (0<=i_skolem) -> (i_skolem<9) ->
  (s[a+i_skolem] <> t[a+8-i_skolem]) ->
  false
```

And to reason modulo the axiom my_inlined_axiom, Alt-Ergo will try to instantiate it to generate finitely many ground consequences and give them to the SAT+[decision procedures].

Instantiation process is guided by the notion of triggers (or patterns). These are, in general, terms that appear in axioms. For instance, possible "good" triggers for my_inlined_axiom are "t[a+i]", "s[a+8-i]". The semantics of instantiation by matching is then as follows: Whenever a (ground) term matches one of these patterns,  the corresponding instance is generated.

In your example, "s[a+i_skolem]" (resp. "t[a+8-i_skolem]") does not match "s[(a+8)-i]" (resp. "t[a+i]"). So no instance is generated.


However, if matching is done modulo arithmetic (which is not done by Alt-Ergo but simulated with "axiom arith"), the result of matching "s[a+i_skolem]" against "s[(a+8)-i]" succeeds and produces the substitution  { i |-> 8 - i_skolem }. The corresponding instance below  will allow you to prove validity.

```
(0<=8-i_skolem) -> (8-i_skolem<9) -> (t[a+8-i_skolem] = s[a+8-(8-i_skolem)])
```

2/ "model candidate" is a terminology used for models that satisfy the ground part of a formula, but not necessarily the universally quantified part.

3/ No, we don't have a public user manual for Alt-Ergo. But all these notions are quite standard in SMT.
