### ISSUE TITLE
Alt-Ergo should use ITIMER_VIRTUAL to measure verification timeouts

### ISSUE THREAD

**Issue by fuzxxl** [OCamlPro/alt-ergo#20]
While trying to verify software on multiple cores, we found that Alt-Ergo requires a higher timeout to verify some proof obligations when multiple instances run at the same time. While some of this can be explained by a slowdown through parallel use of shared resources (i.e. memory bandwidth), it also turns out that when running in parallel, each instance of Alt-Ergo actually aborts after less CPU-time than specified in the timeout.

I believe the cause of this is Alt-Ergo using the `setitimer()` system call with `ITIMER_REAL`, which measures real time. However, for the purpose of aborting the verification process after a certain amount of CPU-time is elapsed, it might be more sensible to use `ITIMER_VIRTUAL` which only measures the time Alt-Ergo is scheduled to run. While other processes run (as is the case under high system load), the timer is stopped, leading to correct timeouts regardless of how frequently the Alt-Ergo process was scheduled to run.

I have written and tested a patch to fix this problem; feel free to include it in a future release:

```
diff -r -u alt-ergo-1.30.orig/src/sat/sat_solvers.ml alt-ergo-1.30/src/sat/sat_solvers.ml
--- alt-ergo-1.30.orig/src/sat/sat_solvers.ml	2016-11-21 07:54:45.000000000 +0100
+++ alt-ergo-1.30/src/sat/sat_solvers.ml	2017-02-17 12:09:42.258261685 +0100
@@ -339,7 +339,7 @@
   let _ =
     if not (model ()) then
       try
-        Sys.set_signal Sys.sigalrm
+        Sys.set_signal Sys.sigvtalrm
 	  (Sys.Signal_handle (fun _ -> Options.exec_timeout ()))
       with Invalid_argument _ -> ()
 
@@ -347,7 +347,7 @@
     if model () then
       fun t ->
         try
-	  Sys.set_signal Sys.sigalrm
+	  Sys.set_signal Sys.sigvtalrm
 	    (Sys.Signal_handle (fun _ ->
 	      printf "%a@." (print_model ~header:true) t;
 	      Options.exec_timeout ()))
diff -r -u alt-ergo-1.30.orig/src/util/myUnix.ml alt-ergo-1.30/src/util/myUnix.ml
--- alt-ergo-1.30.orig/src/util/myUnix.ml	2016-11-21 07:54:45.000000000 +0100
+++ alt-ergo-1.30/src/util/myUnix.ml	2017-02-17 12:08:55.593490797 +0100
@@ -12,11 +12,11 @@
 
   let set_timeout timelimit =
     if Pervasives.(<>) timelimit 0. then
-      ignore (Unix.setitimer Unix.ITIMER_REAL
+      ignore (Unix.setitimer Unix.ITIMER_VIRTUAL
 		{ Unix.it_value = timelimit; Unix.it_interval = 0. })
 
   let unset_timeout () =
-    ignore (Unix.setitimer Unix.ITIMER_REAL
+    ignore (Unix.setitimer Unix.ITIMER_VIRTUAL
 	      { Unix.it_value = 0.; Unix.it_interval = 0. })
 
 end
```

**Comment by OCamlPro-Iguernlala** [comment]
Thanks for the report. We'll consider the application of the patch in the next weeks (I'm on holidays).

**Comment by OCamlPro-Iguernlala** [comment]
I applied the patch. It'll be available in the next release.
