### ISSUE TITLE
Soundness bug.

### ISSUE THREAD

**Issue by squell** [OCamlPro/alt-ergo#21]
With Alt-Ergo 1.30, the following input can be proven, which I believe should not be the case. I do not know if this is related to issue #17, which I assume should be fixed in 1.30.

The problem is also present in Alt-Ergo 1.01, but not in Alt-Ergo 0.99.1.

```ml
logic divides : int, int -> prop

axiom divides_def :
  forall d:int. forall n:int. divides(d, n) ->
  exists q:int. n = q*d

axiom divides_oppl :
  forall a:int. forall b:int. divides(a, b) -> divides(-a, b)

axiom divides_factorl :
  forall a:int. forall b:int. divides(a, b*a)

logic prime : int -> prop

axiom prime_def1 :
  forall p:int. prime(p) ->
  forall n:int. 1 < n < p -> not divides(n, p)

axiom prime_2 : prime(2)

(*
  A suggested interpretation for the next two functions is:

  add(x,y) = x+y
  neg      = -1
*)

logic add : int, int -> int  
logic neg : int

axiom Div_mod :
  forall x:int. forall y:int. x = y*neg + add(x, y)

axiom Mod_minus1_left : 
  forall y:int. add(-1, y) = y - 1

goal Oops : 1 = 2
```

Note: the fact that 2 is hypothesized to be a prime in this file has some bearing on its use in the formula `1 = 2`; if I change the axiom to state that `prime(3)`, you also have to change the goal formula to `1 = 3`, and so on.

(Note that this file is a heavily reduced version of what Why3 generates when I import its `number.Prime` theory.)

**Comment by OCamlPro-Iguernlala** [comment]
Thank you for reporting the bug. We will debug it soon.

**Comment by OCamlPro-Iguernlala** [comment]
The bug is now fixed, and the fix will be available in the next release.
