### ISSUE TITLE
Why is there de dep to alt-ergo from altgr-ergo OPAM file ?

### ISSUE THREAD

**Issue by OriginLabs-Iguernlala** [OCamlPro/alt-ergo#224]
AltGr-Ergo binary does not depend on Alt-Ergo (binary). Is this dependecy in OPAM file due to recent switch to dune build system ? ou can we remove it ?

**Comment by Gbury** [comment]
The dep is indeed superfluous and should be removed.

**Comment by OCamlPro-Coquera** [comment]
fixed in #289
