### ISSUE TITLE
Better error messages ?

### ISSUE THREAD

**Issue by ddeclerck** [OCamlPro/alt-ergo#236]
Some error cases just raise a generic exception, i.e "Fatal error: exception AltErgoLib__Errors.Error(_, _)". It makes it hard to spot typos.

Example 1:
goal g: 1.0 + 1 > 1

Example 2:
logic p: int,int -> prop
goal g: p(1)

**Comment by Gbury** [comment]
When the dolmen parser and typer will be merged, the erorr messages will be substantially better (and include precise positions in source code), though I don't think we plan on supporting the ae native syntax  with dolmen.

**Comment by Gbury** [comment]
See #192

**Comment by OCamlPro-Iguernlala** [comment]
This issue has been introduced recently:

```

**Comment by Coquera** [comment]
should be fix in #237

**Comment by OCamlPro-Iguernlala** [comment]
Fixed !
