### ISSUE TITLE
opam minimal version unclear

### ISSUE THREAD

**Issue by MikolasJanota** [OCamlPro/alt-ergo#254]
For `configure` fails with `opam: unknown command var.`  Possibly I need a different version of `opam`?

**Comment by Gbury** [comment]
Thanks for the report !
The configure script assumed a version of opam >= 2. I just opened a PR to fix that (see #257 ), can you confirm that it fixes your problem (or you can upgrade to opam 2).

**Comment by OriginLabs-Iguernlala** [comment]
Fixed
