### ISSUE TITLE
Windows installer

### ISSUE THREAD

**Issue by pjljvandelaar** [OCamlPro/alt-ergo#258]
As I user I would like a windows/linux/MacOS installer, such that I can just download, install, and use the alt-ergo problem solver.

The current way to use alt-ergo force me to also install OCaml which I never used so far.
Furthermore, I need to download and install a number of libraries, which I don't know where to find.
Although no link to the psmt2-frontend library is provided in the [install instructions](https://github.com/OCamlPro/alt-ergo/blob/next/sources/INSTALL.md), I can rely on my search engine and hope it is indeed https://github.com/OCamlPro-Coquera/psmt2-frontend.
But for the menhir package, even that approach fails and I just get a lot of info on standing stones ;-(

Note that the problem solver is not even my end goal, I want to use tools that use problem solvers like [TorXakis](https://github.com/TorXakis/TorXakis). So I like as many details to be hidden for me as possible!

**Comment by Gbury** [comment]
Sorry for the late answer: we're going to try and see how much work would be needed to provide a windows installer. Out of curiosity, would you need the GUI (i.e. altgr-ergo) too, or simply the alt-ergo binary to execute it ?

**Comment by pjljvandelaar** [comment]
I need a command line interface over which I can communicate smt2.
I don't know whether you have experience with cvc4, z3, and yices
but with them it is
```
cvc4 --lang=smt2.5 --incremental --strings-exp --fmf-fun-rlv --uf-ss-fair --no-strings-print-ascii
```
```
z3 -smt2 -in
```
and
```
yices-smt2 --incremental
```

**Comment by OriginLabs-Iguernlala** [comment]
Hi @pjljvandelaar ,
- for menhir, it'd be better to google "menhir ocaml" to get accurate results. And more generally, the first step is to have a look to package available via OPAM: https://opam.ocaml.org/packages/

For Windows, it's hard and an important cost to maintain a working compilation infra to generate binaries. We only do this on demand, or if we have some sparse time/funding.

From your second message, do you plan to use Alt-Ergo in incremental mode ? If yes, you should know that this feature is currently not supported

**Comment by pjljvandelaar** [comment]
Indeed, I would like to use alt-ergo in incremental mode.
So please let me know when incremental solving is supported. Either via this issue or the TorXakis issue https://github.com/TorXakis/TorXakis/issues/940.

**Comment by OriginLabs-Iguernlala** [comment]
incremental mode support is not planned in short or med term :-/

**Comment by Halbaroth** [comment]
Close this issue because the recommended way to install Alt-Ergo on Windows is through opam 2.2 now.
