### ISSUE TITLE
unsoundness involving integer division on 2.3.0

### ISSUE THREAD

**Issue by alleystoughton** [OCamlPro/alt-ergo#271]
The following unsoundness bug has been fixed in your next branch, but it seems bad to have such a simple and serious outstanding bug in your last public release.

```
goal g1 :
 forall n : int.
 1 < n -> 0 < (n - 1) / 2

(* so let's introduce as an axiom, and then
  try proving false *)

axiom from_g1 :
 forall n : int.
 1 < n -> 0 < (n - 1) / 2

goal g2 :
 false
```

**Comment by OCamlPro-Coquera** [comment]
Hi,
Thank you for bringing the problem to our attention,
we have just released a new minor version 2.3.1 of Alt-Ergo (https://github.com/OCamlPro/alt-ergo/releases/tag/2.3.1) including the bugfix. This release should be available on OPAM soon.

We are always glad to know our users, you can contact us at alt-ergo@ocamlpro.com we will be pleased to talk with you.

Best
