### ISSUE TITLE
assertion failure

### ISSUE THREAD

**Issue by zapashcanon** [OCamlPro/alt-ergo#290]
Hi,

This bug appeared when @Numero7 tried to replay proofs I've made a while back in why3 - when we were working on proving Parcoursup' algorithms with @backtracking.

It happens with alt-ergo 2.3 but not with 2.2.

Here's the output:

```log
Prover output:
Fatal error: exception File "lib/structures/expr.ml", line 1522, characters 2-8: Assertion failed
```

I'm not sure if I can make the why3 files public, but I can at least provide them if needed.

Note that I've never managed to reproduce the bug, only @Numero7 did - many times.

What would be a way to get interesting debug logs for you ?

**Comment by OCamlPro-Coquera** [comment]
Hi,

Thanks for the issues, we will look into it. 

Having the output file sent from why3 to Alt-Ergo could help us a lot and we could save so time checking for different version of Why3. Can you try to use the following command line please:
`why3 prove -D alt_ergo -a split_goal_full <your_file> -L <directory_of_utils_for_your_proof> --output=<output_dir>`
You may need to create `<output_dir>` before running the command.

This line will create multiple files in `<output_dir>` corresponding to each goals to prove in Alt-Ergo format. Then you can try to run Alt-Ergo on this files an provide us (if possible) the one issuing the assertion. With the file issuing this bug it will be easier for us to debug, specially in this case where only one of you have this bug.

**Comment by Numero7** [comment]
Thanks for the feedback.


I reproduced the problem starting with a clean install of why3 and alt-ergo on MAcOSX
> rm -fr ~/.opam
> brew remove opam
> brew install opam
> opam install why3 why3-ide alt-ergo coq why3-coq
> opam install alt-ergo.2.3.1
> why3 config --detect
> why3 prove -D alt_ergo algo1p4.mlw -a split_goal_full -L . --output=tmp
> alt-ergo tmp/algo1p4-P4-rang_diff_in_permutqtvc1.why
Fatal error: exception File "lib/structures/expr.ml", line 1522, characters 2-8: Assertion failed

Attached is the (zipped) file algo1p4-P4-rang_diff_in_permutqtvc1.why

[algo1p4-P4-rang_diff_in_permutqtvc1.why.zip](https://github.com/OCamlPro/alt-ergo/files/4404303/algo1p4-P4-rang_diff_in_permutqtvc1.why.zip)


Regards

**Comment by Numero7** [comment]
After downgrading alt-ergo to 2.2.0, with the same command
 I do not have any errors anymore. Below is the output and attached the why file generated with why3 after alt-ergo has been downgraded

> opam install alt-ergo.2.2.0
> why3 config --detect
> why3 prove -D alt_ergo algo1p4.mlw -a split_goal_full -L . --output=tmp
File "tmp/algo1p4-P4-rang_diff_in_permutqtvc1.why", line 1639, characters 4-808:Valid (0.0444) (95 steps) (goal rang_diff_in_permutqtvc)
[algo1p4-P4-swap_is_permutqtvc1.why.zip](https://github.com/OCamlPro/alt-ergo/files/4404485/algo1p4-P4-swap_is_permutqtvc1.why.zip)

**Comment by OCamlPro-Coquera** [comment]
Thanks for the file, i manage to have the error with Alt-Ergo 2.3.2 and not 2.2.0 on my computer. The file will be helpful for debugging.
We will keep you in touch.

**Comment by Numero7** [comment]
Thanks

Gérald Point is pointing me to a similar issue from last year
https://github.com/OCamlPro/alt-ergo/issues/245

Regards

**Comment by OriginLabs-Iguernlala** [comment]
Fixed by https://github.com/OCamlPro/alt-ergo/pull/325
