### ISSUE TITLE
[Build] add more checks

### ISSUE THREAD

**Issue by ACoquereau** [OCamlPro/alt-ergo#293]
- Loading and running of plugins / parsers
- Loading of preludes
- Make rules (archi, ..) 
- Check if `--where` option results are correct

**Comment by ACoquereau** [comment]
Should https://github.com/OCamlPro/alt-ergo/pull/436 resolve this issue ?

**Comment by Halbaroth** [comment]
- Loading plugins and preludes is tested in cram tests.
- The `--where` option is not tested. We cannot add a cram test because the output depends on the environment. I think that this test is not relevant because the feature is simple and unessential. There is no risk to break it silently.

**Comment by bclement-ocp** [comment]
Moreover `--where` is (mostly) useless now as we use the dune plugin mechanism and embed preludes in the binary.
