### ISSUE TITLE
assertion failure in lib/reasoners/satml.ml

### ISSUE THREAD

**Issue by backtracking** [OCamlPro/alt-ergo#313]
When running Alty-Ergo 2.3.2 on the attached file, we get the following error:
Fatal error: exception File "lib/reasoners/satml.ml", line 1259, characters 20-26: Assertion failed

[bug.zip](https://github.com/OCamlPro/alt-ergo/files/4837555/bug.zip)

**Comment by OriginLabs-Iguernlala** [comment]
This is likely a bug in case-split mechanism. Its explanations/backjumping annotations should "escape its scope" and be seen by the main SAT solver.
