### ISSUE TITLE
Put some laziness in Printer.print_dbg ?

### ISSUE THREAD

**Issue by OriginLabs-Iguernlala** [OCamlPro/alt-ergo#321]
I see a possible regression in performances due to introduction of module `Printer`. I'm thinking of this kind of usage of `Printer.print_dbg`:

```
  print_dbg ~debug "%d" (List.length l);
```

With the old (basic) mecanism, this code would be:
```
if debug then
  Format.fprintf fmt "%d" (List.length l)
``` 

But, with the new mechanism, `List.length l` is executed even if the debug flag is false.

**Comment by Gbury** [comment]
If performance of logging is a concern, then the best would be to use the same convention as the logs library (cf https://github.com/dbuenzli/logs ). See https://github.com/mirage/ocaml-git/pull/130 for a discussion about the various possibilities for logging and why logs is currently the overall best option.

**Comment by OCamlPro-Coquera** [comment]
Will look into it
