### ISSUE TITLE
Is it possible/easy to disable advanced output formatting in logs ?

### ISSUE THREAD

**Issue by OriginLabs-Iguernlala** [OCamlPro/alt-ergo#327]
The use of Format capabilities to output well formatted output is good for humains that read log files, but may prevent searching/grepp-ing for expressions inside the logs. I don't know if it is possible/easy to disable Format's indentations / boxes / lines break when a command-line option is set.

**Comment by Gbury** [comment]
You could use the `Format.pp_set_max_indent`/`Format.pp_set_margin`/`Format.pp_set_geometry` functions and set the max_indent to a small enough value I guess ?

**Comment by OCamlPro-Coquera** [comment]
Maybe with modifying the formatter_out_functions, Redefining `out_indent n = out_indent 0` ?

**Comment by OriginLabs-Iguernlala** [comment]
I usually search for some terms when debugging to see where they are introduced for the first time in the SAT, or theories, ... So, formatting / lines breaking prevent this. When formulas are big, setting indentation to small enough value will not (always) fix the issue I think.

**Comment by OCamlPro-Coquera** [comment]
In the same way as out_indent, we may be able to modify out_newline to prevent line breaking completely ?

**Comment by OCamlPro-Coquera** [comment]
Does #363 do the trick for you @OriginLabs-Iguernlala ?
