### ISSUE TITLE
Do not use colors in solver's final output

### ISSUE THREAD

**Issue by OriginLabs-Iguernlala** [OCamlPro/alt-ergo#333]
It would probably be better to output the solver's answer (sat / unsat / unknwon / valid, ...) without ANSI colors.

For me, it should be as simple as doing `echo $output | grep ^unsat$` to test if the solver answered unsat. But, this doesn't work if the output is colored.

**Comment by OCamlPro-Coquera** [comment]
The options `no-colors-in-output` is here to disabling colors in outputs. You should be able to perform your commands with this option, no ?

**Comment by OCamlPro-Coquera** [comment]
We can also add an option `--clean-ouputs`, and `-c`, that disable colors, headers (for debug) and formatting so you will have exacly what you had previously and we will have something more user friendly without this option ?

**Comment by OriginLabs-Iguernlala** [comment]
Yes, I can. But you cannot/shouldn't ask people who already integrated Alt-Ergo in their tools to activated an option to fix such issues imo.

**Comment by OriginLabs-Iguernlala** [comment]
Also, I noticed that when Alt-Ergo answers eg `sat` or `unsat` when fed with an SMT file, the comment:
```
; File .... : Valid (xxx seconds) (y steps)
```
disapeared. So now, one should perfix commands with `time` to get resolution time :-/

**Comment by OCamlPro-Coquera** [comment]
Since the next version of Alt-Ergo will break retro compatibility because of new options format, from `-<option>` to `--<option>` and `.why` files are marked as obselete (use `.ae` instead) users that integrated Alt-Ergo will be forced to check and change their options. I think a simple option like `-c` to have clean output can be possible no ?
