### ISSUE TITLE
Use `sh` instead of `bash` in configure

### ISSUE THREAD

**Issue by thomasblanc** [OCamlPro/alt-ergo#344]
Discussed with @Gbury who agrees (and wonders whether this should be applied on old versions).

On a minimal machine (say, to run a CI), bash can not be installed.

The weirder thing is, the error message is pretty much "no error message here is an error 127" which makes it appear as if `configure` itself is not found.

Note: there is also a dependency on bash in extra but it's probably less important than configure.

**Comment by Gbury** [comment]
I'll fix that.
While we're at it, we are fortunate enough that in this case, we can patch the oam files in the opam repository to fix that problem in the versions already released (by replacing the `./configure` line with the correct ocaml invocation), without having to craft new minor releases, i'll try and do that as soon as I can.

**Comment by OriginLabs-Iguernlala** [comment]
Ok, I merged Guillaume's PR. For older versions, maybe we can patch OPAM packages if needed ?

**Comment by Gbury** [comment]
Already did that in https://github.com/ocaml/opam-repository/pull/16867

**Comment by OriginLabs-Iguernlala** [comment]
Ah, you did it for all versions that build with Dune :+1:
