### ISSUE TITLE
[Bug] Assertion failure in lib/reasoners/shostak.ml when reasoning on bitv

### ISSUE THREAD

**Issue by LouisRustenholz** [OCamlPro/alt-ergo#350]
Running Alt-Ergo 2.3.2 on the attached file raises the following error :
`Fatal error: exception File "lib/reasoners/shostak.ml", line 491, characters 12-18: Assertion failed`.

[bug.zip](https://github.com/OCamlPro/alt-ergo/files/4982722/bug.zip)

**Comment by Halbaroth** [comment]
The fix does not work with the Dolmen frontend:
```Fatal error: exception File "src/lib/structures/expr.ml", line 2633, characters 8-14: Assertion failed```

**Comment by hra687261** [comment]
Issues should only be closed once the fix was tested and merged.
Also, problems with the PR should be reported on the PR.
