### ISSUE TITLE
Error: Prover 'alt-ergo' not found in why3.conf

### ISSUE THREAD

**Issue by anukaal** [OCamlPro/alt-ergo#360]
Why it is showing this error In 
Error: Prover 'alt-ergo' not found in why3.conf

**Comment by OCamlPro-mattiasdrp** [comment]
Can you show your .why3.conf file?

**Comment by OCamlPro-mattiasdrp** [comment]
Usually the error comes from the fact that you wrote `driver = "alt-ergo"` instead of `driver = "alt_ergo"`

**Comment by anukaal** [comment]
But i guess its not able to detect the prover Alt-ergo


Prover Z3 version 4.8.8 is not known to be supported.
Known versions for this prover: 4.8.0, 4.8.1, 4.8.3, 4.8.4, 4.8.5, 4.8.6.
Known old versions for this prover: .
Prover Alt-Ergo version 2.3.3 is not known to be supported.
Known versions for this prover: 2.3.1, 2.3.0.
Known old versions for this prover: .
Found prover Coq version 8.12.0, but no Why3 libraries were compiled for it
2 prover(s) added (including 2 prover(s) with an unrecognized version)

**Comment by OriginLabs-Iguernlala** [comment]
Can you rename `why3.conf` to eg. `why3.conf.old` and redo `why3 conf --detect-provers` ?

**Comment by anukaal** [comment]
> Can you rename `why3.conf` to eg. `why3.conf.old` and redo `why3 conf --detect-provers` ?

can you elaborate it what's gonna be happen?

**Comment by OCamlPro-mattiasdrp** [comment]
> > Can you show your .why3.conf file?
> 
> Didn't get where it is located in mac

Executing `why3 config` should tell you where it is located ;-)

**Comment by anukaal** [comment]
> > > Can you show your .why3.conf file?
> > 
> > 
> > Didn't get where it is located in mac
> 
> Executing `why3 config` should tell you where it is located ;-)

Still didn't find ...its not showing ;(

**Comment by OCamlPro-mattiasdrp** [comment]
```
❯ why3 config
Save config to /home/mattias/.why3.conf
```
What do you have when you execute `why3 config`

**Comment by anukaal** [comment]
> ```
> ❯ why3 config
> Save config to /home/mattias/.why3.conf
> ```
> 
> 
> What do you have when you execute `why3 config`?

yeah ...same but didn't get any file at this location

**Comment by OCamlPro-mattiasdrp** [comment]
My idea is that Why3 is not able to detect Alt-Ergo because it doesn't accept versions higher that 2.3.1 (which should change in the future but how long is this future is another story). What you should is edit `.why3.conf` to add Alt-Ergo yourself (either by creating it if it doesn't exist or by editing it).

So, step 1:
 - `why3 config --detect`. This should create a new `.why3.conf` file (remember to enable `show hidden files` since files starting with `.` are considered hidden files)
 - Edit `.why3.conf` and add the following lines:
```
[prover]
command = "alt-ergo -t %t %f"
command_steps = "alt-ergo -t %t %f"
driver = "alt_ergo"
editor = ""
in_place = false
interactive = false
name = "Alt-Ergo"
shortcut = "alt-ergo"
version = "2.3.0"
```

Alt-Ergo should then be recognized by Why3

**Comment by anukaal** [comment]
yes its working fine ...but how to change to the new provers from the default one alt-ergo after downloading the new provers

**Comment by OCamlPro-mattiasdrp** [comment]
New provers being new versions of Alt-Ergo or provers like CVC4, Z3 etc?

**Comment by anukaal** [comment]
Not the new version of Alt-ergo , provers mainly CVC4

**Comment by OriginLabs-Iguernlala** [comment]
If you use `opam` to install Alt-Ergo, I think the latest installed version will be the one used by Why3 (regardless the version detected with `why3 config` and shown in why3's config file.
