### ISSUE TITLE
Configuration requires 'opam' to be installed.

### ISSUE THREAD

**Issue by correnson** [OCamlPro/alt-ergo#367]
The configuration of alt-ergo fails if `opam` is not installed.

Problem found under NixOS with opam2nix.

**Comment by Gbury** [comment]
Indeed, running the configure script alone will fail if opam is not installed.
You can however, provide explicit values of `--libdir` and `--prefix` to the configure script, and then it will not call opam anymore.

**Comment by Gbury** [comment]
Note that once #368 is merged, you'll have two options for a opam-less configure:
- provide a value to the `--prefix` option to the configure script, **or**
- provide values for the `--libdir` and `--mandir` options of the configure script
(Admittedly, the fact that it is not already the case is an error on my part when I wrote the configure script)

Additionally, when opam is not installed, the script will now print an error message that will mention these two solutions.

**Comment by correnson** [comment]
Fair enough ! However, I'm afraid it wouldn't work in the case of `opam2nix` environment, since it uses `opam` instructions to install ocaml packages on NixOS… without opam. Hence, we can not modify the configure invocation, which is part of the opam instructions.

**Comment by Gbury** [comment]
Are you able to set the opam configuration variable that may appear in the opam intructions ? E.g. variables such as `%{man}`, `%[lib}`, `%{pkg:bin}` that opam traditionally substitutes before running the commands ?

If so, one potential solution would be for the opam instructions of alt-ergo to call the configure script with explicit values using these opam variables, and then you could do your own substitution on them ?

**Comment by correnson** [comment]
Unfortunately, I'm not involved in the development of `opam2nix`, just using it out of the box 😸

**Comment by Gbury** [comment]
I think it's reasonable to assume `opam2nix` will indeed subtitute opam variables as it's prety much mandatory for packages that use them. I'll try and create a branch so that you can try.

**Comment by Gbury** [comment]
@correnson Could you try on #369 and see if that fixes your problems ?

**Comment by correnson** [comment]
I realize that I can not check without committing the package into an local opam-repository...
This can take some time, but I shall try it… Thanks for the support !

**Comment by OriginLabs-Iguernlala** [comment]
I assume that https://github.com/OCamlPro/alt-ergo/pull/369 fixes the issue. Closing it ...
Feel free to re-open it if there's still something to discuss.
