### ISSUE TITLE
[Gui] move altgr-ergo.conf file in the share/alt-ergo directory of current opam switch

### ISSUE THREAD

**Issue by ACoquereau** [OCamlPro/alt-ergo#430]
Add option to specify share directory in configure

**Comment by ACoquereau** [comment]
This issue was raised by this pr : https://github.com/ocaml/opam-repository/pull/18015 where the conf file could not be create in the  sandbox of opam

**Comment by bclement-ocp** [comment]
Closing as the GUI has been removed in #601
