### ISSUE TITLE
accepting let expressions in terms

### ISSUE THREAD

**Issue by kanigsson** [OCamlPro/alt-ergo#470]
Currently the why3 driver for alt-ergo contains the transformation "eliminate_let_term" to eliminate local let expressions in terms. This transformation can lead to blowups if the variable defined by the let is then used multiple times.
Is there any chance that alt-ergo could support such let expressions directly without the need for elimination?
Note that even if alt-ergo uses the same strategy of inlining let expressions (which can lead to blowups), it would still be better for us compared to the same transformation in why3. It would allow us to use the existing time/step limit mechanisms to bound the running time, while there is no existing mechanism for why3 transformations.
Thanks in advance for considering this request.

**Comment by Stevendeo** [comment]
I'm not sure to follow ; Alt-Ergo does support let expressions in terms.

```
logic x : int

goal test: x > (3 + (let y = 4 in y + 1))
```

I'm not familiar with why3 drivers ; have you tried removing this transformation from the why3 driver ?

**Comment by kanigsson** [comment]
Hello Steven, thanks for your input. Then this is likely an incorrect assumption of the why3 driver. Just removing the transformation is not enough, as the printer actually refuses to print the VC in that case. I will bring this up with the why3 team.
