### ISSUE TITLE
alt-ergo fails to compile without opam

### ISSUE THREAD

**Issue by dwarfmaster** [OCamlPro/alt-ergo#496]
I am using [opam2nix](https://github.com/timbertson/opam2nix) to package for [NixOS](https://nixos.org) a package depending on alt-ergo. It generates instructions to build alt-ergo in an environment without opam, where all the dependencies are managed by Nix. To do so it provides explicitely `mandir` and `libdir`. However I still get the error : 
```shell
 + ocaml unix.cma configure.ml alt-ergo-lib --libdir /nix/store/pycxim2dgybzyzdmq18nckac53ds3a5k-alt-ergo-lib-2.4.0/lib/ocaml/4.12.0/site-lib --mandir /nix/store/pycxim2dgybzyzdmq18nckac53ds3a5k-alt-ergo-lib-2.4.0/man
which: no opam in (...)
ERROR: Couldn't find opam in env.
To solve this, you can either install opam, provide an explicit value to the
`--prefix` argument of this script, or provide explicit values to both the
`--libdir` and `--mandir` options of this
```

After looking at [configure.ml:115](https://github.com/OCamlPro/alt-ergo/blob/c3aca37b25cd53a35d9266e5a5966ce359542f26/configure.ml#L115), it turns out that it tries to set `prefix` even if `mandir` and `libdir` are provided. So either `prefix` is necessary in addition to the other two, in which case the error message should be changed, or the logic should be updated to not try to access `prefix` if `mandir` and `libdir` are set.

**Comment by Gbury** [comment]
I've opened #497 which should fix configure to behave like the error message specifies.

**Comment by Gbury** [comment]
One small problem when not specifying a `--prefix` is that it's not clear where to install the binaries. Unfortunately, `dune install` does not have a `--bindir` option, and thus without a prefix the `make install` rule is broken.

Actually, that brings me to the question of how you install the files once it is built ? Do you use the `make install` target, or do you use the `.install` files generated by `dune` (like `opam` does) ? If you use the install files, we could then deprecate/remove the `make install` target, and the problem would be solved.

**Comment by dwarfmaster** [comment]
It uses the `.install` file by calling [opam-installer](https://opam.ocaml.org/packages/opam-installer/), and when it does that it gives it the `--prefix` option, so `make install` is not necessary for this.
