### ISSUE TITLE
Prooving an invalid statement

### ISSUE THREAD

**Issue by strub** [OCamlPro/alt-ergo#5]
Hi,

Here is an (invalid) statement that should not be accepted by Alt-Ergo.

  goal A : forall x : real. forall y : real.
    0. <= x -> 1. <= y -> x / y = x \* 1. / y -> 0. < x

**Comment by strub** [comment]
Replayable in 0.99.1. That's super neat !

**Comment by iguer** [comment]
We are sorry, but we have limited resources, and we cannot spend time to propagate bugfixes into old public or private releases (unless someone requests for the maintainance of a particular version).

Btw, the bug is not replayable with version 1.00 (http://alt-ergo.ocamlpro.com/try.php)

**Comment by strub** [comment]
I was just surprised because 0.99 came out 4 months after this issue has been closed.

In any case, I'll do the fix on my side.

**Comment by iguer** [comment]
Private version 0.99 was tagged in October 2013. Version 0.99.1 (publically released last December) is almost similar to 0.99 (we have just removed an experimental component).
