### ISSUE TITLE
Alt-ergo is incompatible with cmdliner 1.1.0

### ISSUE THREAD

**Issue by fblanqui** [OCamlPro/alt-ergo#503]
Hello. Do you plan to make a new release compatible with cmdliner 1.1.0 soon? Best regards, Frédéric.

**Comment by Gbury** [comment]
Hi @fblanqui ! A minor release is indeed imminent, and it will include support for cmdliner version 1.1.0 and onwards (see PR #502 )

**Comment by fblanqui** [comment]
Salut Guillaume! Super. Merci.

**Comment by SnarkBoojum** [comment]
The mentioned minor release didn't happen yet ; perhaps the issue was closed too early?

**Comment by fblanqui** [comment]
When will happen the release?
