### ISSUE TITLE
Build fails on many architectures

### ISSUE THREAD

**Issue by SnarkBoojum** [OCamlPro/alt-ergo#509]
From the [Debian build logs](https://buildd.debian.org/status/package.php?p=alt-ergo), there are failures on many architectures with the same error:
```
File "src/plugins/AB-Why3/dune", line 24, characters 5-22:
24 |     (ABWhy3Plugin.cmxs as plugins/AB-Why3-plugin.cmxs)
          ^^^^^^^^^^^^^^^^^
Error: No rule found for src/plugins/AB-Why3/ABWhy3Plugin.cmxs
File "src/plugins/fm-simplex/dune", line 17, characters 5-25:
17 |     (FmSimplexPlugin.cmxs as plugins/fm-simplex-plugin.cmxs)
          ^^^^^^^^^^^^^^^^^^^^
Error: No rule found for src/plugins/fm-simplex/FmSimplexPlugin.cmxs
```
and I have to admit I don't know why some architectures know how to build that file and not others... perhaps a case of buggy opt/native support?

**Comment by SnarkBoojum** [comment]
I can confirm my hunch: the renaming lines for .cmxs files in the two `src/plugins/*/dune` files are the problem, as the files don't exist on non-native architectures!

**Comment by Stevendeo** [comment]
PR #524 fixes it
