### ISSUE TITLE
[Error](0 <= (0 - 1)) is not a term, is_lit = true

### ISSUE THREAD

**Issue by xldenis** [OCamlPro/alt-ergo#519]
AltErgo 2.4.1 crashes on the following file with the above error message.

The error case was generated in Why3. 

(Zipped for the GH filters..)
[01_resolve_unsoundness-C01ResolveUnsoundness_MakeVecOfSize-make_vec_of_sizeqtvc_1.ae.zip](https://github.com/OCamlPro/alt-ergo/files/9185811/01_resolve_unsoundness-C01ResolveUnsoundness_MakeVecOfSize-make_vec_of_sizeqtvc_1.ae.zip)

**Comment by Stevendeo** [comment]
Thanks for the feedback! I pushed a fix that concludes the file is Valid; is it the correct answer?

**Comment by xldenis** [comment]
Indeed, this file should be SAT. Thanks for the quick fix!

**Comment by Stevendeo** [comment]
Bad luck, the quick fix was unsound. I updated a new version of the fix, but even if it does not fail anymore, alt-ergo does not manage to conclude.

**Comment by xldenis** [comment]
That's already better than a crash!

**Comment by bclement-ocp** [comment]
@Stevendeo looks like this is solved by #520, should we close?
