### ISSUE TITLE
Wrong version number with `--version`

### ISSUE THREAD

**Issue by gcluzel** [OCamlPro/alt-ergo#523]
Hi all,

I have installed  alt-ergo 2.4.2 with opam. When I run `alt-ergo --version` I get `dev`. This is a bit unfortunate that 2.4.2 is not displayed instead as why3 provers detection is based on the version number printed by this option.

Do you think that it would be easy to correct this issue?

**Comment by Stevendeo** [comment]
Hi, yes I will fix that, sorry for the mistake!

**Comment by Stevendeo** [comment]
This should be fixed now: with `opam update` and `opam upgrade`, `alt-ergo --version` should print `2.4.2`.
