### ISSUE TITLE
Error during the installation of alt-ergo 2.4.2 with opam

### ISSUE THREAD

**Issue by gcluzel** [OCamlPro/alt-ergo#547]
I recently noticed that the `url` in the .opam file in the official  [opam-repositiory](https://github.com/ocaml/opam-repository/blob/master/packages/alt-ergo/alt-ergo.2.4.2/opam) for alt-ergo 2.4.2 does not correctly work.

In particular, when I try to install `alt-ergo` with opam, I get the following errors:
```
#10 687.3 #=== ERROR while fetching sources for alt-ergo-parsers.2.4.2 ==================#
#10 687.3 OpamSolution.Fetch_fail("https://github.com/OCamlPro/alt-ergo/archive/2.4.2.tar.gz (Bad checksum, expected md5=c47327ae132c860890c820bfd5d49d51)")
#10 687.3 
#10 687.3 #=== ERROR while fetching sources for alt-ergo-lib.2.4.2 ======================#
#10 687.3 OpamSolution.Fetch_fail("https://github.com/OCamlPro/alt-ergo/archive/2.4.2.tar.gz (Bad checksum, expected md5=c47327ae132c860890c820bfd5d49d51)")
#10 687.3 
#10 687.3 #=== ERROR while fetching sources for alt-ergo.2.4.2 ==========================#
#10 687.3 OpamSolution.Fetch_fail("https://github.com/OCamlPro/alt-ergo/archive/2.4.2.tar.gz (Bad checksum, expected md5=c47327ae132c860890c820bfd5d49d51)")
#10 694.5 
#10 694.5 
#10 694.5 <><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
#10 694.5 +- The following actions failed
#10 694.5 | - fetch alt-ergo         2.4.2
#10 694.5 | - fetch alt-ergo-lib     2.4.2
#10 694.5 | - fetch alt-ergo-parsers 2.4.2
```

After more investigations, it seems that the url https://github.com/OCamlPro/alt-ergo/archive/2.4.2.tar.gz does not correctly work and return an error message and a code 300, because there is a branch called `2.4.2` and also a tag.

In this case, if you want to keep the branch and the tag, you will probably have to disambiguate the url with something more precise like https://github.com/OCamlPro/alt-ergo/archive/refs/tags/2.4.2.tar.gz.

**Comment by AllanBlanchard** [comment]
I didn't see this issue, I opened a PR on opam-repository:

https://github.com/ocaml/opam-repository/pull/23172

However, it seems that the Opam maintainers prefer not relying on github tags. Do you know when it could be fixed? Currently, some of our (Frama-C) CI pipelines related to Opam fail because we cannot install this dependency.

**Comment by Halbaroth** [comment]
Fixed https://github.com/ocaml/opam-repository/pull/23172
