### ISSUE TITLE
Wrongly typed tester with enum constructor

### ISSUE THREAD

**Issue by Halbaroth** [OCamlPro/alt-ergo#551]
Both legacy and Dolmen parsers accept a wrongly typed entry. More precisely, the below file
```
type t = A | B

function h() : t = A

goal g : (h ? A)
```
should be refused since the type `t` is an `enum` and the tester `(_ ? _)` is defined for the type `adt` only. Running Alt-Ergo on this entry produces an `assert false` in `adt_rel.ml`.

**Comment by Gbury** [comment]
Quick comment (on my phone): an enum is a special case of an adt (it's an adt where there are no payload on the constructors). In particular, it makes sense to have testers for it.

**Comment by Halbaroth** [comment]
I know but there is no support for testers in the current `enum` theory. AE converts ADT without payload as an enum.

**Comment by Halbaroth** [comment]
A possible fix consists in adding the support for trivial testers and destructors in enum and record theories to handle the case AE performs a simplification of an ADT. For the record case, I guess AE doesn't keep a trace of the useless constructor...

Another option consists in translating the term `(x ? A)` by `x = A` in the case of a constructor of enum type for instance.

**Comment by Halbaroth** [comment]
I modified the typechecker in the above PR to translate on the fly the tester on enum by an equality. It is not the best design in my opinion but I had no other choice since the transformation of trivial adts have been done before the typechecker. @Gbury  if you agree with this modification, I will make a similar one in Dolmen soon.

**Comment by Gbury** [comment]
While this transformation is an acceptable quick-fix, it should not go in `dolmen` but rather in the translation from `dolmen`'s typed terms to alt-ergo's hashconsed terms.

For a more long-term fix, we basically have two choices for theories concerning adts (and thus enums): to avoid duplication of code and logic, these theories should only reason about 1) pattern matching, or 2) tester and destructors. Once we have decided, it's rather the a question of translating everything into the form that we want to reason on (i.e. pattern matchings can be replaces by a series of if-then-else using testers and destructors, and conversely, formulas using testers and destructors can be replaced by pattern matching).

**Comment by Halbaroth** [comment]
I thought the same thing. It is just a quick fix. In my opinion, we should merge the theories enum, record and adt. If there are important optimizations in enum or record theories, we could keep them by adding a `kind` field in the semantic values of the adt theories.

Currently, there is no real pattern matching. Instead, Alt-Ergo transforms pattern matching from the entry to a bunch of ite using testers (this is done in the function `compile_match`). I found there had a plan to introduce pattern matching in a old roadmap. Is there a good reason to choose this approach?

**Comment by Halbaroth** [comment]
Fixed by #552
