### ISSUE TITLE
Get rid of the legacy front-end?

### ISSUE THREAD

**Issue by hra687261** [OCamlPro/alt-ergo#556]
Alt-Ergo should only have one front-end, it's very annoying to have to do any changes to the front-end twice, once in Alt-Ergo, once in Dolmen.
If more testing needs to be done, then it should be a priority to do it and fix the eventual issues that would come up with switching to Dolmen.

**Comment by Halbaroth** [comment]
I totally agree that we should get rid of it as soon as possible. But we should be sure the actually parser in Dolmen behaves closely like the legacy one. We have very few files in the native input format, which means we didn't test it properly. 
Maybe, we could produce some tests for Dolmen before removing the legacy parser?

We should also check the support of `psmt` in Dolmen.

**Comment by hra687261** [comment]
We can probably generate a good amount of them from Why3's test-suite.
Also once printers become available in Dolmen we can translate some of them.
But I think it should be a priority, because it significantly slows down development whenever someones touches the frontend.

**Comment by bclement-ocp** [comment]
Blocked by #585 and #586

**Comment by hra687261** [comment]
Closing this issue since the legacy front end was removed with OCamlPro/alt-ergo#1251
