### ISSUE TITLE
Dolmen frontend does not support standard input

### ISSUE THREAD

**Issue by bclement-ocp** [OCamlPro/alt-ergo#586]
Consider:

```shell
$ echo 'goal g: true' | alt-ergo --frontend legacy -i alt-ergo -o smtlib2
; File "", line 1, characters 9-13: Valid (0.0001) (0 steps) (goal g)
; 
unsat
$ echo 'goal g: true' | alt-ergo --frontend legacy -i alt-ergo -o smtlib2
Fatal error: exception Sys_error(": No such file or directory")
```

**Comment by Gbury** [comment]
There is a semi-good reason for not being able to read stdin: alt-ergo's native syntax is ambiguous and does not allow to determine the end of a top-level phrase (see [this comment](https://github.com/Gbury/dolmen/blob/a5632a000a8c4ed10c7653574fdf9d9af11a0b05/src/languages/ae/parser.mly#L19-L27) ). In general it's not possible to have a reasonable behaviour when readin ae's native language on stdin: if you want a stream of phrases, you need to start parsing a phrase to know the previous phrase has ended. I guess you could parse it as a file **if** you somehow get an eof at the end.

**Comment by Halbaroth** [comment]
We can fix this issue as soon as we deprecate the native language. Or we can accept only smt2 language on stdin?

**Comment by bclement-ocp** [comment]
I'm not sure this is relevant as the issue is not about streamed parsing. We do get an EOF when standard input is closed, as demonstrated by the fact that the legacy frontend deals with stdin input fine.

Also, if we decide that we don't want to support stdin anymore, the error message should state that explicitly rather than raise a naked OCaml exception.

**Comment by Gbury** [comment]
Oh, if we get an eof when stdin is closed, then we should be able to make ti work (it just won't be usable as a top-level, but that's not a problem).

**Comment by bclement-ocp** [comment]
I think this is just a matter of "legacy frontend interprets no filename as stdin while dolmen frontend tries to open a file with empty name".

**Comment by Gbury** [comment]
that might be it indeed
