### ISSUE TITLE
Removing the javascript support of the repository

### ISSUE THREAD

**Issue by Halbaroth** [OCamlPro/alt-ergo#589]
The current state of the CI is a mess. Until the next random update of `js_of_ocaml` or `ocaml-setup`, it works but still its instability is unsustainable for long terms. 

I suggest to remove completely the directory `src/bin/js` of this repository and to move it on another repository. On this new repository, we will put only a CI on linux and we will update it only for new releases of TryAltErgo since it is the only user of this part of the code.

**Comment by bclement-ocp** [comment]
Can we keep the js support in this repository and simply not test for it on other platforms?

I'd assume it's mostly a matter of moving `alt-ergo-js.opam` and related files to a subdirectory (but with dune and opam you never know).

**Comment by Halbaroth** [comment]
@Gbury  told me it is safer to keep the code in this repository because if we start to use the some code that cannot be compiled into JS, we couldn't realize it quickly. 
The issue comes from the fact I add a package to specify the `js_of_ocaml`, which means the Window CI tries to compile AE into JS. I have a simple idea. We could pin the version of `js_of_ocaml` in approriate target of the Makefile. In this way, we get rid of `alt-ergo-js.opam`.

**Comment by bclement-ocp** [comment]
Agreed that sounds better

**Comment by Gbury** [comment]
Also, we don't really need to compile to js on windows: as long as we can compile to js on linux, that's enough i'd say: once it's compiled to js, one can then execute the js on any machine/os (that's kind of the point of js in theory).

**Comment by Halbaroth** [comment]
This is the reason why I will remove the opam file. Otherwise the command `opam install .` will compile AE into JS on Windows since we distribute AE with sources only.

**Comment by Gbury** [comment]
You could also keep the opam file, and in it specify a constraint that makes it not available on windows.

**Comment by Halbaroth** [comment]
The Makefile will be simpler and safer.
