### ISSUE TITLE
Big_int.num_bits_big_int

### ISSUE THREAD

**Issue by JuliaLawall** [OCamlPro/alt-ergo#61]
When compiling alt-ergo, I get:

File "/home/jll/alt-ergo/sources/lib/util/numsNumbers.ml", line 125, characters 16-40:
Error: Unbound value Big_int.num_bits_big_int
Hint: Did you mean num_digits_big_int?

In what version of the Big_int library is num_bits_big_int defined?

**Comment by OCamlPro-Iguernlala** [comment]
It has been introduced in OCaml 4.03.0. But, num library is not part of OCaml since release 4.06.0 and should be installed separately.

**Comment by OCamlPro-Iguernlala** [comment]
Maybe related to https://github.com/OCamlPro/alt-ergo/issues/66
