### ISSUE TITLE
Assertion failure in "src/lib/reasoners/bitv.ml", line 538

### ISSUE THREAD

**Issue by hra687261** [OCamlPro/alt-ergo#645]
With the following test:
```
logic X: bitv[7]

goal g4: X^{2,5} = X^{2,3} @ X^{5,6}
```

**Comment by Halbaroth** [comment]
The bug is also present in Alt-Ergo 2.4.3. I checked because we modified this module recently.

**Comment by Halbaroth** [comment]
Besides, it seems to be unable to prove the statement:
```
logic X: bitv[7]

goal g4: X^{2,5} = X^{2,3} @ X^{4,5}
```

**Comment by hra687261** [comment]
> Besides, it seems to be unable to prove the statement:
> 
> ```
> logic X: bitv[7]
> 
> goal g4: X^{2,5} = X^{2,3} @ X^{4,5}
> ```

That is normal, bit-vectors are indexed from right to left, so if you provide it with: 
```
logic X: bitv[7]

goal g3: X^{2,5} = X^{4,5} @ X^{2,3}
```
AE will manage to prove it
