### ISSUE TITLE
Add documentation for new features

### ISSUE THREAD

**Issue by bclement-ocp** [OCamlPro/alt-ergo#648]
- [x] Document `float` and FPA #762 
- [x] Document `--frontend dolmen`
- [x] Verify that models API is up-to-date #759 
- [x] BitVectors #762

**Comment by bclement-ocp** [comment]
Not sure that there is much to document wrt the new prelude options; that should just be in the release notes probably (we usually don't document random options, and I don't think `--disable-theories` / `--enable-theories` deserve special treatment. Also the main difference is that the `--use-fpa` and `--prelud` with a FPA theory are no longer necessary, should we document non-options?)

See #763

**Comment by Halbaroth** [comment]
I agree :)
