### ISSUE TITLE
[bitv] Make B and C substitutions be nonrecursive

### ISSUE THREAD

**Issue by bclement-ocp** [OCamlPro/alt-ergo#689]
What I mean was that, when we create the substitution, we could create a substitution of a var to a list.

AFAIK, yes, the substitutions are created in `slice_composition` when the size of the variable is bigger than the pattern. What I meant above is, instead of just looking at a variable `v` and a pattern `p`, we can have something that looks into the next patterns and check if the newly produced variable (the one on the right) doesn't need splitting as well? And if it is the case, the created substitution will map the original variables to all the produced splits.

_Originally posted by @hra687261 in https://github.com/OCamlPro/alt-ergo/issues/680#issuecomment-1603883867_

**Comment by bclement-ocp** [comment]
@hra687261 should I assign you to this one?

**Comment by bclement-ocp** [comment]
(I suggested doing it but actually it is fairly orthogonal to the other changes I made PR about)

**Comment by hra687261** [comment]
Sure!

**Comment by bclement-ocp** [comment]
Random remark: rather than checking if the newly produced variable needs splitting, we probably should not create it at all if it will be immediately split.

**Comment by bclement-ocp** [comment]
I think that for B substitutions it is a bit harder because when we split the other occurences of a variable we can also introduce new splits to an existing variable, so we may be stuck with the recursive substitution for B subs
