### ISSUE TITLE
support ite

### ISSUE THREAD

**Issue by florianschanda** [OCamlPro/alt-ergo#70]
Hi,

When generating VCs for alt-ergo using Why3, there is a particular transformation "eliminate_ite" that sometimes crashes (it runs out of memory). It is my understanding that this is there because Alt-Ergo does not support an ITE construct.

Perhaps you could add it so that we can remove that transformation from why3?

**Comment by OCamlPro-Iguernlala** [comment]
Hi,
Yes, we ar e planning to took at this soon. This is also a serious limitation for us to handle smtlib language

**Comment by OCamlPro-Iguernlala** [comment]
Done ! the next step is to map SMT-LIB's FP theory to Alt-Ergo's theory
