### ISSUE TITLE
check-sat-assuming prints wrong models

### ISSUE THREAD

**Issue by bclement-ocp** [OCamlPro/alt-ergo#707]
Because `process_decl` returns the "next" state, not the "SAT/I_dont_know" state.

`process_decl` should expose the *last* SAT/I_dont_know it encounters as part of its return type (which should not replace the sat_env it currently return, but be an additional argument — probably we should return a record rather than a tuple at this point)

**Comment by bclement-ocp** [comment]
I think @Halbaroth wanted to take that one, assigning him

**Comment by Halbaroth** [comment]
Yes :D

**Comment by Halbaroth** [comment]
Could you clarify a bit the issue? I tried to reproduce the bug as follow: 
```
(set-logic ALL)
(set-option :produce-models true)
(declare-fun f (Int) Int)
(assert (forall ((x Int) (y Int)) (= (f (+ x y)) (+ (f x) (f y)))))
(assert (= (f 0) 0))
(define-fun g () Bool (= (f 1) 1))
(check-sat-assuming (g))
(get-model)
```
But Alt-Ergo prints a correct model:
```
unknown
(
  
 ; Functions

(define-fun f ((arg_0 Int)) Int (ite (= arg_0 1) 1 0))

 ; Constants

(define-fun g () Bool true)

 ; Arrays not yet supported


)
```

**Comment by Halbaroth** [comment]
Besides, we should fix the fact AE modifies defined function in the input file. I will create an issue for that.

**Comment by bclement-ocp** [comment]
Hm, it looks like this only happens with the legacy frontend. It's probably fine then.

Right, so this would only be the case if we supported printing a model after `check_sat` in the AE language, which we don't (models in the AE language can only be obtained by using `--dump-models` currently). We can probably close this, then.

**Comment by Halbaroth** [comment]
Ok :)
