### ISSUE TITLE
Annoying warnings produced by the Dolmen frontend

### ISSUE THREAD

**Issue by Halbaroth** [OCamlPro/alt-ergo#708]
The frontend Dolmen produces warnings for some unsupported statement in `d_cnf.ml`. For instance the input file:
```
(set-logic QF_BV)
(declare-const R (_ BitVec 1))
(set-info :status unsat)

(assert
  (=
    (_ bv1 1)
    (ite
      (=
        (_ bv1 4)
        (bvand
          (_ bv1 4)
          (bvlshr (_ bv0 4) ((_ zero_extend 3) R))))
      (_ bv1 1)
      (_ bv0 1))))

(check-sat)
```
produces the output
```
Ignoring statement: other_2[49-73]:
                      set-info: (:status unsat)
Fatal error: exception Failure("Unsupported Application Term bvand bv#0001#\n                             (bvlshr bv#0000# (zero_extend_3 R))")
```

Dolmen produces some statements that have to be ignored by d_cnf without warnings.

**Comment by bclement-ocp** [comment]
Note that this is intended, because we should *explicitly* list the statements to ignore rather than have a fallthrough case that we silently ignore (you had the issue when adding check-sat if I remember correctly?), you should just add the `Set_info` (and probably `get_info` as well) to the list of "known statements that it is OK to ignore".

**Comment by hra687261** [comment]
Personally, I think we sometimes just don't care and don't want to see what was ignored. That's the case with test files we don´t have the intention of reading anyway.
I had this issue when running tests on the smt-lib, I've had like 10 assertion failures and I just wanted to see where they happened and if they were the same or not, but I had many warnings on the stdout so I had to scroll down to see the assertion failure. In such I case, you probably don't care about warning and care only about unsoundness and crashes.

Edit: So having something like a `-q|--quiet` option that stops see warnings from appearing would be great.

**Comment by Halbaroth** [comment]
I agree for the quiet option.

**Comment by bclement-ocp** [comment]
I think you misunderstood what I am saying, I fully agree (this is why we disable Dolmen's warnings about undefined symbols as well for instance). We must make a conscious decision of whether the type of terms should be ignored or not (e.g. we want to ignore `set-logic` and `set-info`), but we *DON'T* want to ignore a new variant of `Solve` or some such.

I just didn't go through all the possible dolmen constructors. I just opened #710  to ignore `Get_info` and `Set_info`, if there are other constructors that should be ignored, please make corresponding PRs as well.

**Comment by Halbaroth** [comment]
I think you misunderstood what I am saying. I totally agree we have to display a warning message for most of the ignored statements and ignore silently few of them. I just opened this issue as a reminder.

Besides, I agree we should add a quiet option anyway.

**Comment by bclement-ocp** [comment]
>  I totally agree we have to display a warning message for most of the ignored statements and ignore silently few of them.

We disagree then? I think it is a bug that needs to be fixed whenever this warning message pops up (either by explicitly ignoring the corresponding constructor, or handling it if it is semantically meaningful). We shouldn't need a quiet option for these warnings, because they *should not appear*, and if they do, that's a bug.
