### ISSUE TITLE
get-model prints models even if the status of the goal is `unsat`

### ISSUE THREAD

**Issue by Halbaroth** [OCamlPro/alt-ergo#719]
I was playing with Why3, trying to prove my specification of a quick sort. My PO looks like that:
```
(set-logic ALL)
(set-option :produce-models true)
(declare-const a (Array Int Int))
(declare-const s Int)
(assert (and (<= 0 s) (<= s 10)))
(assert (forall ((k Int)) (=> (and (<= 0 k) (< k s)) (<= (select a k) (select a s)))))
(assert (forall ((k Int)) (=> (and (< s k) (<= k 10)) (<= (select a s) (select a k)))))
(assert (
  forall ((p Int) (q Int))
    (=> (and (<= 0 p) (< p q) (<= q (- s 1))) (<= (select a p) (select a q)))))
(assert (
  forall ((p Int) (q Int))
    (=> (and (<= (+ s 1) p) (< p q) (<= q 10)) (<= (select a p) (select a q)))))
(assert (not (
  forall ((p Int) (q Int))
    (=> (and (<= 0 p) (< p q) (<= q 10)) (<= (select a p) (select a q))))))
(check-sat)
(get-model)
```
Z3 and Alt-Ergo prove that the context is `unsat` but AE produces a model... 
```
unsat
(
  (define-fun s () Int 0)
  (define-fun a () (Array Int Int)
   (store (store (as @a (Array Int Int)) 1 0) 0 2))
)
```
I guess I did something wrong in my implementation of `get-model`. I will fix it for the release.

**Comment by bclement-ocp** [comment]
Weird, I thought that we did take care of this properly by unsetting the `partial_model` key?

**Comment by bclement-ocp** [comment]
Also given that we have various options related to models/dolmen currently we should take the habit of giving the command line used to describe the issues (I did the same mistake in #707).

I can reproduce your issue with:
```bash
$ alt-ergo --frontend dolmen --produce-models 719.smt2
```

**Comment by bclement-ocp** [comment]
Ah, no, we only unset the partial model on timeout. I think the fix needs to be similar to what I described in #707 to have `process_decl` return additionally the result of the last query, iff it is a Sat or I_dont_know.

**Comment by Halbaroth** [comment]
I used the command 
```
$ alt-ergo --frontend dolmen --sat-solver tableaux 719.smt2
```
