### ISSUE TITLE
macOS build is broken

### ISSUE THREAD

**Issue by bclement-ocp** [OCamlPro/alt-ergo#740]
Because the error messages from Dynlink are different, yay :)

Not sure how to fix this properly, tbh. Maybe we should have different tests for linux/macOS, or maybe we should rewrite the test slightly.

(We shouldn't hide the message from dylink from the output anyways, because that is helpful information for users)

```
-            >> Failure message: error loading shared library: Dynlink.Error (Dynlink.Cannot_open_dll "Failure(\"$TESTCASE_ROOT/does-not-exist: cannot open shared object file: No such file or directory\")")
+            >> Failure message: error loading shared library: Dynlink.Error (Dynlink.Cannot_open_dll "Failure(\"dlopen($TESTCASE_ROOT/does-not-exist, 0x000A): tried: '$TESTCASE_ROOT/does-not-exist' (no such file)\")")
```

**Comment by Halbaroth** [comment]
A naive solution consists in removing the platform-dependent part of the error message with a command like `grep` or `awk`. I guess a POSIX-compliant grep is available in the Mac OS CI.
