### ISSUE TITLE
Allow configuration of output channel for `--dump-models`

### ISSUE THREAD

**Issue by bclement-ocp** [OCamlPro/alt-ergo#799]
Alt-Ergo uses the standard input to print models. This is in accordance to the SMT-LIB standard.

However, while this makes sense for the models that are printed as a result of a `(get-model)` command from the user, it makes less sense for the models printed by the `--dump-models` option. We should consider printing *those* to stderr by default, and bring back an option to let the user control this output channel independently.

(Seel also #393)

**Comment by Halbaroth** [comment]
I guess this issue is solved?

**Comment by bclement-ocp** [comment]
Yes fixed in #838
