### ISSUE TITLE
steps-bound not reliable on 0.99.1

### ISSUE THREAD

**Issue by clairedross** [OCamlPro/alt-ergo#8]
Hello,
while trying the 0.99.1, I noticed that sometimes, the solver does not seem to increase the number of steps in a long time. I have tests on which the solver returns at once with -steps-bound 40 and takes really long with -steps-bound 50. I will send you some of them if you are interested.
Best regards,
Claire

**Comment by iguer** [comment]
The current -steps-bound option only considers the number of calls (triggered by the SAT solver) to the function assume of the "decision procedures" part.

But, one can easily extend it to a tuple to also include:
- the number of internal case-splits performed by decision procedures, and/or
- the number of decisions made by the SAT, and/or
- the max decision level reached by the SAT, and/or
- the number of instances generated by the matching module and/or
- ...

All these information are recorded by the "profiling plugin" in devel versions of Alt-Ergo.
