### ISSUE TITLE
Proper support for quoted identifiers in models

### ISSUE THREAD

**Issue by bclement-ocp** [OCamlPro/alt-ergo#806]
By the way we probably have a problem with quoted identifiers as well… This is unrelated to this PR however.

_Originally posted by @bclement-ocp in https://github.com/OCamlPro/alt-ergo/issues/804#issuecomment-1714038192_
            

We do.

```console
$ cat quoted.smt2
(set-logic ALL)
(declare-const |fail))| Int)
(assert (= |fail))| 0))
(check-sat)
(get-model)
$ alt-ergo --frontend dolmen --produce-models quoted.smt2
                                       
; File "quoted.smt2", line 4, characters 1-12: I don't know (0.4269) (1 steps) (goal g_1)

unknown
(
  (define-fun fail)) () Int 0)
)
```

**Comment by bclement-ocp** [comment]
Assigning @Halbaroth who said he was interested in tackling this

**Comment by Stevendeo** [comment]
There are few ways to tackle this issue. If Dolmen does not provide the information that the identifier was defined quoted (which would be IMO the best way to do to precisely match the user input), we can : 
- quote all the names in the output (easy, no cost, 100% sound)
- check all names when they are built or printed that they do not contain special characters (not as easy, negligible-but-existent cost, error prone)
