### ISSUE TITLE
Unable to build on Mageia Cauldron with ocaml-compiler-4.06.0

### ISSUE THREAD

**Issue by kekePower** [OCamlPro/alt-ergo#82]
Hi.

I'm trying to build version 2.1.0 on Mageia Cauldron, but am unsuccessful.

This is the message I get.

`alt-ergo/BUILD/alt-ergo-2.1.0/lib/reasoners/intervalCalculus.ml", line 196, characters 14-72:`
`Error: This expression has type Sim.Core.t`
`       but an expression was expected of type 'weak1 * 'weak2`
`make: *** [Makefile.users:292: lib/reasoners/intervalCalculus.cmx] Error 2`

I'm a packager, not a programmer, so I have no idea how to fix this.
Any help is much appreciated.

Cheers,
kekePower

**Comment by OCamlPro-Iguernlala** [comment]
Hi, You are probably using an old (incompatible) version of ocplib-simplex. Can you try with version 0.4 ?

**Comment by kekePower** [comment]
@OCamlPro-Iguernlala 
Thanks. That did it. Now I'm facing another issue, on ARMv7 this time.
About 100 lines of this sort:
`/tmp/camlasma73a5f.s:34274: Error: value of 210286 too large for field of 2 bytes at 61170`

You can see the whole build log here:
http://pkgsubmit.mageia.org/uploads/failure/cauldron/core/release/20180323174601.kekepower.duvel.27477/log/alt-ergo-2.1.0-2.mga7/build.0.20180323174609.log

**Comment by OCamlPro-Iguernlala** [comment]
This is probably an OCaml related issue. It seems there is a kind of integer overflow during compilation. What do you think @chambart ?

**Comment by OCamlPro-Iguernlala** [comment]
Hi. Can you share the content of the .s file produced during the error

`
Error: Assembler error, input left in file /tmp/camlasma73a5f.s
`

**Comment by kekePower** [comment]
Hi @OCamlPro-Iguernlala 

I'm sorry, but I don't have access to the Build System and at the same time, the build is done in a chroot that gets deleted afterwards.

**Comment by OCamlPro-Iguernlala** [comment]
Ok. As I said in a previous comment, this is rather an OCaml issue. This is probably related to the way of compiling jumps.
