### ISSUE TITLE
Enable warnings as errors on the CI

### ISSUE THREAD

**Issue by bclement-ocp** [OCamlPro/alt-ergo#879]
The warning is enabled but we don't have warning as errors on. It is good for local development (when building locally, we see the warnings and can make an informed decision about whether to treat them as errors now or fix them later to try things), but we should definitely use a profile with `-warn-error +A` on the CI, yes.

_Originally posted by @bclement-ocp in https://github.com/OCamlPro/alt-ergo/pull/861#discussion_r1354312642_

**Comment by Halbaroth** [comment]
I will do it :)

**Comment by Halbaroth** [comment]
Solved by #888
