### ISSUE TITLE
Add support for `get-objectives`

### ISSUE THREAD

**Issue by Halbaroth** [OCamlPro/alt-ergo#891]

**Comment by bclement-ocp** [comment]
We should use the `(get-objectives)` command supported by Z3 and OptiMathSAT and hence de-facto standard rather than a custom `get-info` flag.

**Comment by Gbury** [comment]
Does that mean that `(get-objectives)` is a statement that is commonly used along `(minimize ...)` and `(maximize ...)` ? If so I'll add it to the `maxsmt` extension in Dolmen. Also, if there are other statements commonly used for maxsmt, it'd be useful to know.

**Comment by bclement-ocp** [comment]
> Does that mean that `(get-objectives)` is a statement that is commonly used along `(minimize ...)` and `(maximize ...)` ? If so I'll add it to the `maxsmt` extension in Dolmen.

[*ahem*](https://github.com/Gbury/dolmen/blob/master/src/standard/extensions.ml#L34) :sweat_smile: 

> Also, if there are other statements commonly used for maxsmt, it'd be useful to know.

For Z3: [Optmization](https://microsoft.github.io/z3guide/docs/optimization/arithmeticaloptimization) and [soft constraints](https://microsoft.github.io/z3guide/docs/optimization/softconstraints) 

For OptiMathSAT: https://optimathsat.disi.unitn.it/pages/smt2reference.html

Those two are the solvers I know that implement MaxSMT extensions in the SMT-LIB format; the common ones are `minimize`, `maximize`, `get-objectives` and `assert-soft` which are those currently in Dolmen's MaxSMT extension.

**Comment by Gbury** [comment]
> > Does that mean that `(get-objectives)` is a statement that is commonly used along `(minimize ...)` and `(maximize ...)` ? If so I'll add it to the `maxsmt` extension in Dolmen.
> 
> [_ahem_](https://github.com/Gbury/dolmen/blob/master/src/standard/extensions.ml#L34) 😅

Point taken, I should sleep a bit more, :p
