### ISSUE TITLE
A->B quickly rejected as "dont know", while AA->B quickly provable, with AA an unfolded version of A

### ISSUE THREAD

**Issue by Jochen-Burghardt** [OCamlPro/alt-ergo#9]
The following file has been boiled down from Frama-C output:
```
type addr = { base : int; offset : int }
logic addr_le : addr, addr -> prop

axiom addr_le_def :
  (forall p:addr. forall q:addr [addr_le(p, q)]. (((p).base = (q).base) ->
  (addr_le(p, q) -> ((p).offset <= (q).offset))))

axiom addr_le_def1 :
  (forall p:addr. forall q:addr [addr_le(p, q)]. (((p).base = (q).base) ->
  (((p).offset <= (q).offset) -> addr_le(p, q))))

function shift(p: addr, k: int) : addr = { base = (p).base; offset = ((p).offset + k) }

goal A_B:
  forall a_2,a : addr.
  addr_le(a_2, a) ->
  addr_le(a_2, shift(a, 1)) 
```
Running Alt-Ergo (version 0.95.2) on it gives "I don't know" after 0.14 sec (real time, measured with linux command "time").
However, when the goal is replaced by a version with the first "addr_le" unfolded, viz.
```
goal AA_B:
  forall a_2,a : addr.
  a_2.base = a.base ->
  a_2.offset <= a.offset ->
  addr_le(a_2, shift(a, 1))
```
then Alt-Ergo proves it after 0.13 sec. 
I wonder why Alt-Ergo apparently not even tries to prove the goal A_B, but almost immediately rejects it. As a consequence, Frama-C/Alt-Ergo is rather weak on address arithmetic, while it is much stronger on ordinary arithmetic.

Btw: If the second "addr_le" is unfolded, viz.:
```
goal A_BB:
  forall a_2,a : addr.
  addr_le(a_2, a) ->
  a_2.base = shift(a, 1).base and
  a_2.offset <= shift(a, 1).offset
```
then Alt-Ergo again rejects the file as "dont know" after 0.13 sec.
If both "addr_le" are unfolded, viz.
```
goal AA_BB:
  forall a_2,a : addr.
  a_2.base = a.base ->
  a_2.offset <= a.offset ->
  a_2.base = shift(a, 1).base and
  a_2.offset <= shift(a, 1).offset
```
then Alt-Ergo proves the goal in 0.12 sec.
It seems that the first "addr_le" prevents Alt-Ergo from trying a proof.

**Comment by iguer** [comment]
Unfolding the first "addr_le" in goal_A_B yields

```
goal AA_B_well_parenthesized:
  forall a_2,a : addr.
  (
    a_2.base = a.base ->
    a_2.offset <= a.offset
   )
   ->
  addr_le(a_2, shift(a, 1))
```

which is not equivalent to 
```
goal AA_B:
  forall a_2,a : addr.
  a_2.base = a.base ->
  a_2.offset <= a.offset ->
  addr_le(a_2, shift(a, 1))
```

**Comment by Jochen-Burghardt** [comment]
You are right - I had a blind spot when reading the axiom "addr_le_def". Thank you for pointing it out. I now submitted the issue to the Frama-C BTS, see https://bts.frama-c.com/view.php?id=2047.
